# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy

version: 0.2

env:
  variables:
    PROJECT: leap_dashboard_admin_api

phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore

  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c Release  -r linux-x64 -o ./build_output ./leap_dashboard_admin_api/leap_dashboard_admin_api.csproj
  
artifacts:
  files:
    - "**/*"
  base-directory: ./build_output
  discard-paths: no
  
